import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { apiRequest } from "../../api/client";
import { errorMessage } from "../../api/errors";
import type { ApplicationSummary, DirectoryGroupMember, DirectoryGroupSummary, PagedResult, RoleSummary, UserSummary } from "../../api/types";
import { useSession } from "../../auth/session";
import { Breadcrumbs } from "../../components/Breadcrumbs";
import { ConfirmDialog } from "../../components/ConfirmDialog";
import { HistoryLink } from "../../components/HistoryLink";
import { PageHeader } from "../../components/PageHeader";
import { PageState } from "../../components/PageState";
import { Pagination } from "../../components/Pagination";
import { StatusBadge } from "../../components/StatusBadge";
import { useDebouncedValue } from "../../hooks/useDebouncedValue";
import { buildQuery, formatDate } from "../../utils/format";
import { groupDefaults, groupPayload, groupSchema, type GroupFormValues } from "./group";

export default function GroupEditorPage({ create = false }: { create?: boolean }) {
  const { permissions } = useSession();
  const canWrite = permissions.has("AUTHCENTER_GROUPS_WRITE");
  const canReadUsers = permissions.has("AUTHCENTER_USERS_READ");
  const canReadApplications = permissions.has("AUTHCENTER_APPLICATIONS_READ");
  const canReadRoles = permissions.has("AUTHCENTER_ROLES_READ");
  const { groupId } = useParams();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [params, setParams] = useSearchParams();
  const memberPage = Math.max(1, Number(params.get("memberPage")) || 1);
  const memberPageSize = [20, 50, 100].includes(Number(params.get("memberPageSize"))) ? Number(params.get("memberPageSize")) : 20;
  const [memberSearch, setMemberSearch] = useState("");
  const debouncedMemberSearch = useDebouncedValue(memberSearch);
  const [applicationOverrides, setApplicationOverrides] = useState<Map<string, boolean>>(new Map());
  const [roleOverrides, setRoleOverrides] = useState<Map<string, boolean>>(new Map());
  const [memberToRemove, setMemberToRemove] = useState<DirectoryGroupMember | null>(null);
  const [confirmStatus, setConfirmStatus] = useState(false);
  const [feedback, setFeedback] = useState("");

  const group = useQuery({ queryKey: ["group", groupId], enabled: !create && Boolean(groupId), queryFn: ({ signal }) => apiRequest<DirectoryGroupSummary>(`/api/groups/${groupId}`, { signal }) });
  const members = useQuery({ queryKey: ["group-members", groupId, memberPage, memberPageSize], enabled: !create && Boolean(groupId), queryFn: ({ signal }) => apiRequest<PagedResult<DirectoryGroupMember>>(`/api/groups/${groupId}/members?${buildQuery({ page: memberPage, pageSize: memberPageSize })}`, { signal }) });
  const candidates = useQuery({ queryKey: ["users", "group-candidates", debouncedMemberSearch], enabled: !create && canReadUsers && debouncedMemberSearch.length >= 2, queryFn: ({ signal }) => apiRequest<PagedResult<UserSummary>>(`/api/users?${buildQuery({ page: 1, pageSize: 20, search: debouncedMemberSearch, isActive: true })}`, { signal }) });
  const applications = useQuery({ queryKey: ["applications", "group-access"], enabled: !create && canReadApplications, queryFn: ({ signal }) => apiRequest<PagedResult<ApplicationSummary>>("/api/applications?page=1&pageSize=100", { signal }) });
  const roles = useQuery({ queryKey: ["roles", "group-access"], enabled: !create && canReadRoles, queryFn: ({ signal }) => apiRequest<PagedResult<RoleSummary>>("/api/roles?page=1&pageSize=100", { signal }) });
  const form = useForm<GroupFormValues>({ resolver: zodResolver(groupSchema), defaultValues: groupDefaults() });
  useEffect(() => { if (group.data) form.reset(groupDefaults(group.data)); }, [form, group.data]);

  const selectedApplications = useMemo(() => deriveSelection(group.data?.applications.map((application) => application.id) ?? [], applicationOverrides), [applicationOverrides, group.data?.applications]);
  const selectedRoles = useMemo(() => deriveSelection(group.data?.roles.map((role) => role.id) ?? [], roleOverrides), [group.data?.roles, roleOverrides]);
  const memberIds = new Set(members.data?.items.map((member) => member.userId) ?? []);
  const editableAccess = canWrite && group.data?.isActive && canReadApplications && canReadRoles;
  const save = useMutation({ mutationFn: (values: GroupFormValues) => apiRequest<DirectoryGroupSummary>(create ? "/api/groups" : `/api/groups/${groupId}`, { method: create ? "POST" : "PUT", body: JSON.stringify(groupPayload(values)) }), onSuccess: async (saved) => { queryClient.setQueryData(["group", saved.id], saved); await queryClient.invalidateQueries({ queryKey: ["groups"] }); if (create) navigate(`/groups/${saved.id}`, { replace: true }); else { form.reset(groupDefaults(saved)); setFeedback("La identidad del grupo quedó actualizada."); } } });
  const saveAccess = useMutation({ mutationFn: () => apiRequest<DirectoryGroupSummary>(`/api/groups/${groupId}/access`, { method: "PUT", body: JSON.stringify({ applicationSystemIds: [...selectedApplications], roleIds: [...selectedRoles].filter((roleId) => { const role = roles.data?.items.find((item) => item.id === roleId); return role?.applicationSystemId && selectedApplications.has(role.applicationSystemId); }) }) }), onSuccess: async (saved) => { queryClient.setQueryData(["group", saved.id], saved); setApplicationOverrides(new Map()); setRoleOverrides(new Map()); await queryClient.invalidateQueries({ queryKey: ["groups"] }); setFeedback("El acceso heredado quedó actualizado de forma atómica."); } });
  const addMember = useMutation({ mutationFn: (userId: string) => apiRequest<void>(`/api/groups/${groupId}/members/${userId}`, { method: "POST" }), onSuccess: async () => { setMemberSearch(""); await Promise.all([queryClient.invalidateQueries({ queryKey: ["group-members", groupId] }), queryClient.invalidateQueries({ queryKey: ["group", groupId] }), queryClient.invalidateQueries({ queryKey: ["groups"] })]); setFeedback("El miembro fue agregado y sus sesiones anteriores fueron revocadas."); } });
  const removeMember = useMutation({ mutationFn: (userId: string) => apiRequest<void>(`/api/groups/${groupId}/members/${userId}`, { method: "DELETE" }), onSuccess: async () => { setMemberToRemove(null); await Promise.all([queryClient.invalidateQueries({ queryKey: ["group-members", groupId] }), queryClient.invalidateQueries({ queryKey: ["group", groupId] }), queryClient.invalidateQueries({ queryKey: ["groups"] })]); setFeedback("La membresía fue retirada y sus sesiones anteriores fueron revocadas."); } });
  const changeStatus = useMutation({ mutationFn: () => apiRequest<void>(`/api/groups/${groupId}/${group.data?.isActive ? "deactivate" : "activate"}`, { method: "PATCH" }), onSuccess: async () => { setConfirmStatus(false); await Promise.all([queryClient.invalidateQueries({ queryKey: ["group", groupId] }), queryClient.invalidateQueries({ queryKey: ["groups"] })]); setFeedback("El estado del grupo quedó actualizado."); } });

  if (!create && group.isPending) return <PageState title="Cargando grupo" busy />;
  if (!create && group.isError) return <PageState title="No pudimos cargar el grupo" detail={errorMessage(group.error)} tone="error" />;
  const current = group.data;
  const title = create ? "Nuevo grupo" : current?.name ?? "Grupo";
  return <>
    <Breadcrumbs items={[{ label: "Grupos", to: "/groups" }, { label: title }]} />
    <PageHeader eyebrow="Directorio" title={title} description={canWrite ? "Administra identidad, membresías y acceso heredado con revocación de sesiones." : "Consulta el grupo y su acceso efectivo. Tu sesión es de sólo lectura."} actions={<>{create ? null : <HistoryLink entityName="DirectoryGroup" entityId={groupId} />}<Link className="button button--secondary" to="/groups">Volver</Link></>} />
    {feedback ? <p className="alert alert--success" role="status">{feedback}</p> : null}{save.error || saveAccess.error || addMember.error || removeMember.error ? <p className="alert alert--error" role="alert">{errorMessage(save.error ?? saveAccess.error ?? addMember.error ?? removeMember.error)}</p> : null}
    <form className="settings-form" onSubmit={(event) => void form.handleSubmit((values) => save.mutateAsync(values))(event)}><fieldset className="settings-fieldset" disabled={!canWrite}><section className="settings-panel"><div className="settings-panel__heading"><div><h2>Identidad</h2><p>Los nombres se comparan sin distinguir mayúsculas para evitar duplicados.</p></div>{current ? <StatusBadge active={current.isActive} /> : null}</div><Field label="Nombre" error={form.formState.errors.name?.message}><input {...form.register("name")} /></Field><Field label="Descripción" error={form.formState.errors.description?.message}><textarea {...form.register("description")} rows={3} /></Field></section></fieldset>{canWrite ? <div className="form-footer"><Link className="button button--secondary" to="/groups">Cancelar</Link><button className="button" disabled={save.isPending}>{save.isPending ? "Guardando…" : create ? "Crear grupo" : "Guardar identidad"}</button></div> : null}</form>
    {current ? <><AccessPanel group={current} applications={applications.data?.items ?? []} roles={roles.data?.items ?? []} selectedApplications={selectedApplications} selectedRoles={selectedRoles} catalogReadable={canReadApplications && canReadRoles} editable={Boolean(editableAccess)} busy={saveAccess.isPending} onApplicationChange={(id, enabled) => { setApplicationOverrides((map) => new Map(map).set(id, enabled)); if (!enabled) setRoleOverrides((map) => { const next = new Map(map); roles.data?.items.filter((role) => role.applicationSystemId === id).forEach((role) => next.set(role.id, false)); return next; }); }} onRoleChange={(id, enabled) => setRoleOverrides((map) => new Map(map).set(id, enabled))} onSave={() => saveAccess.mutate()} />
      <section className="settings-panel settings-panel--actions" aria-labelledby="group-members"><div className="settings-panel__heading"><div><h2 id="group-members">Miembros</h2><p>Todos heredan las aplicaciones y roles mostrados arriba. Los cambios revocan sesiones activas.</p></div><span className="tag">{current.memberCount} miembros</span></div>{canReadUsers ? <><label className="field field--search"><span>Agregar usuario</span><input type="search" value={memberSearch} onChange={(event) => setMemberSearch(event.target.value)} disabled={!canWrite || !current.isActive} placeholder="Busca por nombre o correo" /></label>{debouncedMemberSearch.length >= 2 ? <div className="candidate-list" aria-label="Usuarios encontrados">{candidates.data?.items.filter((user) => !memberIds.has(user.id)).map((user) => <div className="candidate-item" key={user.id}><span><strong>{user.fullName}</strong><small>{user.email}</small></span><button type="button" className="button button--small button--secondary" disabled={!canWrite || addMember.isPending} onClick={() => addMember.mutate(user.id)}>Agregar</button></div>)}</div> : null}</> : <p className="alert alert--info">Necesitas AUTHCENTER_USERS_READ para buscar nuevos miembros.</p>}{members.isPending ? <p className="muted">Cargando miembros…</p> : null}{members.data?.items.length ? <><div className="data-table" tabIndex={0} role="region" aria-label="Miembros del grupo"><table><caption className="sr-only">Miembros del grupo</caption><thead><tr><th>Usuario</th><th>Estado</th><th>Agregado</th><th><span className="sr-only">Acciones</span></th></tr></thead><tbody>{members.data.items.map((member) => <tr key={member.userId}><td><strong>{member.fullName}</strong><span className="cell-detail">{member.email}</span></td><td><StatusBadge active={member.isActive} /></td><td>{formatDate(member.addedAt)}</td><td className="table-action">{canWrite ? <button type="button" className="button button--small button--danger-quiet" onClick={() => setMemberToRemove(member)}>Retirar</button> : null}</td></tr>)}</tbody></table></div><Pagination page={members.data.page} pageSize={members.data.pageSize} totalCount={members.data.totalCount} totalPages={members.data.totalPages} onPageChange={(value) => updateMemberParam("memberPage", value)} onPageSizeChange={(value) => updateMemberParam("memberPageSize", value)} /></> : <p className="muted">El grupo aún no tiene miembros.</p>}</section>
      {canWrite ? <section className="settings-panel settings-panel--actions"><div className="settings-panel__heading"><div><h2>Operación</h2><p>Desactivar el grupo retira inmediatamente su contribución al acceso efectivo.</p></div></div><button className={`button ${current.isActive ? "button--danger-quiet" : "button--secondary"}`} onClick={() => setConfirmStatus(true)}>{current.isActive ? "Desactivar" : "Activar"}</button></section> : null}</> : null}
    <ConfirmDialog open={memberToRemove !== null} title="Retirar miembro" detail={memberToRemove ? `${memberToRemove.fullName} perderá el acceso heredado del grupo y sus sesiones serán revocadas.` : ""} confirmLabel="Retirar miembro" dangerous busy={removeMember.isPending} onCancel={() => setMemberToRemove(null)} onConfirm={() => { if (memberToRemove) removeMember.mutate(memberToRemove.userId); }} />
    <ConfirmDialog open={confirmStatus} title={`${current?.isActive ? "Desactivar" : "Activar"} grupo`} detail="El cambio revocará las sesiones de sus miembros para recalcular el acceso efectivo." confirmLabel={current?.isActive ? "Desactivar" : "Activar"} dangerous={Boolean(current?.isActive)} busy={changeStatus.isPending} onCancel={() => setConfirmStatus(false)} onConfirm={() => changeStatus.mutate()} />
  </>;

  function updateMemberParam(name: string, value: number): void { setParams((currentParams) => { const next = new URLSearchParams(currentParams); next.set(name, String(value)); if (name === "memberPageSize") next.set("memberPage", "1"); return next; }); }
}

function AccessPanel({ group, applications, roles, selectedApplications, selectedRoles, catalogReadable, editable, busy, onApplicationChange, onRoleChange, onSave }: { group: DirectoryGroupSummary; applications: ApplicationSummary[]; roles: RoleSummary[]; selectedApplications: Set<string>; selectedRoles: Set<string>; catalogReadable: boolean; editable: boolean; busy: boolean; onApplicationChange: (id: string, enabled: boolean) => void; onRoleChange: (id: string, enabled: boolean) => void; onSave: () => void }) {
  return <section className="settings-panel settings-panel--actions" aria-labelledby="group-access"><div className="settings-panel__heading"><div><h2 id="group-access">Acceso heredado</h2><p>Preview: {group.memberCount} miembros recibirán {selectedApplications.size} aplicaciones y {selectedRoles.size} roles.</p></div></div>{!catalogReadable ? <p className="alert alert--info">Necesitas permisos de lectura de aplicaciones y roles para modificar el acceso.</p> : <div className="access-grid"><fieldset className="check-group"><legend>Aplicaciones</legend><div className="permission-matrix">{applications.length ? applications.map((application) => <label className="permission-option" key={application.id}><input type="checkbox" checked={selectedApplications.has(application.id)} disabled={!editable || !application.isActive} onChange={(event) => onApplicationChange(application.id, event.target.checked)} /><span><strong>{application.name}</strong><small className="mono">{application.code}</small></span></label>) : <p className="muted">No hay aplicaciones disponibles.</p>}</div></fieldset><fieldset className="check-group"><legend>Roles por aplicación</legend><div className="permission-matrix">{roles.filter((role) => role.applicationSystemId && role.name !== "SuperAdmin").length ? roles.filter((role) => role.applicationSystemId && role.name !== "SuperAdmin").map((role) => <label className={`permission-option ${role.isActive ? "" : "permission-option--inactive"}`} key={role.id}><input type="checkbox" checked={selectedRoles.has(role.id)} disabled={!editable || !role.isActive || !selectedApplications.has(role.applicationSystemId!)} onChange={(event) => onRoleChange(role.id, event.target.checked)} /><span><strong>{role.name}</strong><small>{applications.find((application) => application.id === role.applicationSystemId)?.name ?? "Aplicación"}</small></span></label>) : <p className="muted">No hay roles delegables disponibles.</p>}</div></fieldset></div>}{editable ? <div className="form-footer"><button type="button" className="button" disabled={busy} onClick={onSave}>{busy ? "Guardando…" : "Guardar acceso heredado"}</button></div> : null}</section>;
}

function deriveSelection(initial: string[], overrides: Map<string, boolean>): Set<string> { const selected = new Set(initial); for (const [id, enabled] of overrides) { if (enabled) selected.add(id); else selected.delete(id); } return selected; }
function Field({ label, error, children }: { label: string; error: string | undefined; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}{error ? <span className="field-error">{error}</span> : null}</label>; }
