// <auto-generated />
using System;
using AuthCenter.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthCenter.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuthCenterDbContext))]
    partial class AuthCenterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthCenter.Domain.Entities.ApplicationRegistrationSettings", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<Guid>("ApplicationSystemId").HasColumnType("uniqueidentifier");
                b.Property<string>("AllowedEmailDomains").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<bool>("AllowGoogleLogin").HasColumnType("bit");
                b.Property<bool>("AllowPasswordLogin").HasColumnType("bit");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<Guid?>("DefaultRoleId").HasColumnType("uniqueidentifier");
                b.Property<int>("RegistrationMode").HasColumnType("int");
                b.Property<bool>("RequireEmailConfirmation").HasColumnType("bit");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("ApplicationSystemId").IsUnique();
                b.ToTable("ApplicationRegistrationSettings");
            });

            modelBuilder.Entity("AuthCenter.Domain.Entities.ApplicationSystem", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("Code").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("Code").IsUnique();
                b.ToTable("ApplicationSystems");
            });

            modelBuilder.Entity("AuthCenter.Domain.Entities.AuditLog", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("Action").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("ApplicationCode").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("EntityId").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("EntityName").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("IpAddress").HasMaxLength(45).HasColumnType("nvarchar(45)");
                b.Property<string>("MetadataJson").HasColumnType("nvarchar(max)");
                b.Property<string>("UserAgent").HasMaxLength(512).HasColumnType("nvarchar(512)");
                b.Property<Guid?>("UserId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("Action");
                b.HasIndex("CreatedAt");
                b.HasIndex("UserId");
                b.ToTable("AuditLogs");
            });

            modelBuilder.Entity("AuthCenter.Domain.Entities.ExternalIdentityProvider", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("DisplayName").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<DateTime>("LinkedAt").HasColumnType("datetime2");
                b.Property<DateTime?>("LastUsedAt").HasColumnType("datetime2");
                b.Property<string>("PictureUrl").HasMaxLength(2048).HasColumnType("nvarchar(2048)");
                b.Property<string>("Provider").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("ProviderUserId").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.HasIndex("Provider", "ProviderUserId").IsUnique();
                b.ToTable("ExternalIdentityProviders");
            });

            modelBuilder.Entity("AuthCenter.Domain.Entities.Permission", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<Guid>("ApplicationSystemId").HasColumnType("uniqueidentifier");
                b.Property<string>("Code").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.HasKey("Id");
                b.HasIndex("ApplicationSystemId", "Code").IsUnique();
                b.ToTable("Permissions");
            });

            modelBuilder.Entity("AuthCenter.Domain.Entities.RefreshToken", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime>("ExpiresAt").HasColumnType("datetime2");
                b.Property<string>("IpAddress").HasMaxLength(45).HasColumnType("nvarchar(45)");
                b.Property<string>("ReplacedByTokenHash").HasMaxLength(512).HasColumnType("nvarchar(512)");
                b.Property<DateTime?>("RevokedAt").HasColumnType("datetime2");
                b.Property<string>("TokenHash").IsRequired().HasMaxLength(512).HasColumnType("nvarchar(512)");
                b.Property<string>("UserAgent").HasMaxLength(512).HasColumnType("nvarchar(512)");
                b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("TokenHash").IsUnique();
                b.HasIndex("UserId");
                b.ToTable("RefreshTokens");
            });

            modelBuilder.Entity("AuthCenter.Domain.Entities.RolePermission", b =>
            {
                b.Property<Guid>("RoleId").HasColumnType("uniqueidentifier");
                b.Property<Guid>("PermissionId").HasColumnType("uniqueidentifier");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.HasKey("RoleId", "PermissionId");
                b.HasIndex("PermissionId");
                b.ToTable("RolePermissions");
            });

            modelBuilder.Entity("AuthCenter.Domain.Entities.UserApplicationAccess", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<Guid>("ApplicationSystemId").HasColumnType("uniqueidentifier");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<DateTime?>("RevokedAt").HasColumnType("datetime2");
                b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("ApplicationSystemId");
                b.HasIndex("UserId", "ApplicationSystemId").IsUnique();
                b.ToTable("UserApplicationAccesses");
            });

            modelBuilder.Entity("AuthCenter.Domain.Entities.ApplicationRole", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<Guid?>("ApplicationSystemId").HasColumnType("uniqueidentifier");
                b.Property<string>("ConcurrencyStamp").HasColumnType("nvarchar(max)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Description").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<bool>("IsSystemRole").HasColumnType("bit");
                b.Property<string>("Name").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.HasKey("Id");
                b.HasIndex("ApplicationSystemId");
                b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex").HasFilter("[NormalizedName] IS NOT NULL");
                b.ToTable("AspNetRoles");
            });

            modelBuilder.Entity("AuthCenter.Domain.Entities.ApplicationUser", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<int>("AccessFailedCount").HasColumnType("int");
                b.Property<string>("ConcurrencyStamp").HasColumnType("nvarchar(max)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Email").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<bool>("EmailConfirmed").HasColumnType("bit");
                b.Property<string>("FullName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<bool>("HasLocalPassword").HasColumnType("bit");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<bool>("IsExternalUser").HasColumnType("bit");
                b.Property<DateTime?>("LastLoginAt").HasColumnType("datetime2");
                b.Property<bool>("LockoutEnabled").HasColumnType("bit");
                b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("datetimeoffset");
                b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("PasswordHash").HasColumnType("nvarchar(max)");
                b.Property<string>("PhoneNumber").HasColumnType("nvarchar(max)");
                b.Property<bool>("PhoneNumberConfirmed").HasColumnType("bit");
                b.Property<string>("PictureUrl").HasMaxLength(2048).HasColumnType("nvarchar(2048)");
                b.Property<string>("SecurityStamp").HasColumnType("nvarchar(max)");
                b.Property<bool>("TwoFactorEnabled").HasColumnType("bit");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.Property<string>("UserName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.HasKey("Id");
                b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
                b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex").HasFilter("[NormalizedUserName] IS NOT NULL");
                b.ToTable("AspNetUsers");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ClaimType").HasColumnType("nvarchar(max)");
                b.Property<string>("ClaimValue").HasColumnType("nvarchar(max)");
                b.Property<Guid>("RoleId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("RoleId");
                b.ToTable("AspNetRoleClaims");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ClaimType").HasColumnType("nvarchar(max)");
                b.Property<string>("ClaimValue").HasColumnType("nvarchar(max)");
                b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("AspNetUserClaims");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
            {
                b.Property<string>("LoginProvider").HasColumnType("nvarchar(450)");
                b.Property<string>("ProviderKey").HasColumnType("nvarchar(450)");
                b.Property<string>("ProviderDisplayName").HasColumnType("nvarchar(max)");
                b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                b.HasKey("LoginProvider", "ProviderKey");
                b.HasIndex("UserId");
                b.ToTable("AspNetUserLogins");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
            {
                b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                b.Property<Guid>("RoleId").HasColumnType("uniqueidentifier");
                b.HasKey("UserId", "RoleId");
                b.HasIndex("RoleId");
                b.ToTable("AspNetUserRoles");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
            {
                b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                b.Property<string>("LoginProvider").HasColumnType("nvarchar(450)");
                b.Property<string>("Name").HasColumnType("nvarchar(450)");
                b.Property<string>("Value").HasColumnType("nvarchar(max)");
                b.HasKey("UserId", "LoginProvider", "Name");
                b.ToTable("AspNetUserTokens");
            });

            // Relationships
            modelBuilder.Entity("AuthCenter.Domain.Entities.ApplicationRegistrationSettings", b =>
            {
                b.HasOne("AuthCenter.Domain.Entities.ApplicationSystem", "ApplicationSystem")
                    .WithOne("RegistrationSettings")
                    .HasForeignKey("AuthCenter.Domain.Entities.ApplicationRegistrationSettings", "ApplicationSystemId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("ApplicationSystem");
            });

            modelBuilder.Entity("AuthCenter.Domain.Entities.ApplicationRole", b =>
            {
                b.HasOne("AuthCenter.Domain.Entities.ApplicationSystem", "ApplicationSystem")
                    .WithMany("Roles")
                    .HasForeignKey("ApplicationSystemId")
                    .OnDelete(DeleteBehavior.SetNull);
                b.Navigation("ApplicationSystem");
            });

            modelBuilder.Entity("AuthCenter.Domain.Entities.ExternalIdentityProvider", b =>
            {
                b.HasOne("AuthCenter.Domain.Entities.ApplicationUser", "User")
                    .WithMany("ExternalIdentityProviders")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("AuthCenter.Domain.Entities.Permission", b =>
            {
                b.HasOne("AuthCenter.Domain.Entities.ApplicationSystem", "ApplicationSystem")
                    .WithMany("Permissions")
                    .HasForeignKey("ApplicationSystemId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("ApplicationSystem");
            });

            modelBuilder.Entity("AuthCenter.Domain.Entities.RefreshToken", b =>
            {
                b.HasOne("AuthCenter.Domain.Entities.ApplicationUser", "User")
                    .WithMany("RefreshTokens")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("AuthCenter.Domain.Entities.RolePermission", b =>
            {
                b.HasOne("AuthCenter.Domain.Entities.ApplicationRole", "Role")
                    .WithMany("RolePermissions")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("AuthCenter.Domain.Entities.Permission", "Permission")
                    .WithMany("RolePermissions")
                    .HasForeignKey("PermissionId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Permission");
                b.Navigation("Role");
            });

            modelBuilder.Entity("AuthCenter.Domain.Entities.UserApplicationAccess", b =>
            {
                b.HasOne("AuthCenter.Domain.Entities.ApplicationSystem", "ApplicationSystem")
                    .WithMany("UserApplicationAccesses")
                    .HasForeignKey("ApplicationSystemId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("AuthCenter.Domain.Entities.ApplicationUser", "User")
                    .WithMany("ApplicationAccesses")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("ApplicationSystem");
                b.Navigation("User");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
            {
                b.HasOne("AuthCenter.Domain.Entities.ApplicationRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
            {
                b.HasOne("AuthCenter.Domain.Entities.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
            {
                b.HasOne("AuthCenter.Domain.Entities.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
            {
                b.HasOne("AuthCenter.Domain.Entities.ApplicationRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("AuthCenter.Domain.Entities.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
            {
                b.HasOne("AuthCenter.Domain.Entities.ApplicationUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
            });

            modelBuilder.Entity("AuthCenter.Domain.Entities.ApplicationRole", b =>
            {
                b.Navigation("RolePermissions");
            });

            modelBuilder.Entity("AuthCenter.Domain.Entities.ApplicationSystem", b =>
            {
                b.Navigation("Permissions");
                b.Navigation("RegistrationSettings");
                b.Navigation("Roles");
                b.Navigation("UserApplicationAccesses");
            });

            modelBuilder.Entity("AuthCenter.Domain.Entities.ApplicationUser", b =>
            {
                b.Navigation("ApplicationAccesses");
                b.Navigation("ExternalIdentityProviders");
                b.Navigation("RefreshTokens");
            });

            modelBuilder.Entity("AuthCenter.Domain.Entities.Permission", b =>
            {
                b.Navigation("RolePermissions");
            });
#pragma warning restore 612, 618
        }
    }
}
