import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { Link, useParams } from "react-router-dom";
import { fetchAllAsPage } from "../../api/catalog";
import { apiRequest } from "../../api/client";
import { errorMessage } from "../../api/errors";
import type { ApplicationSummary, ProfileAttributeDefinition, RoleSummary, UserProfile, UserSummary } from "../../api/types";
import { useSession } from "../../auth/session";
import { Breadcrumbs } from "../../components/Breadcrumbs";
import { ConfirmDialog } from "../../components/ConfirmDialog";
import { HistoryLink } from "../../components/HistoryLink";
import { SaveError } from "../../components/SaveError";
import { PageHeader } from "../../components/PageHeader";
import { PageState } from "../../components/PageState";
import { ReauthenticationDialog } from "../../components/ReauthenticationDialog";
import { StatusBadge } from "../../components/StatusBadge";
import { formatDate } from "../../utils/format";
import { userIdentityDefaults, userIdentityPayload, userIdentitySchema, type UserIdentityForm } from "./user";

export default function UserEditorPage() {
  const { userId } = useParams();
  const { permissions } = useSession();
  const canWrite = permissions.has("AUTHCENTER_USERS_WRITE");
  const canReadCatalog = permissions.has("AUTHCENTER_APPLICATIONS_READ") && permissions.has("AUTHCENTER_ROLES_READ");
  const canReadSchema = permissions.has("AUTHCENTER_PROFILE_SCHEMAS_READ");
  const queryClient = useQueryClient();
  const [applicationOverrides, setApplicationOverrides] = useState<Map<string, boolean>>(new Map());
  const [roleOverrides, setRoleOverrides] = useState<Map<string, boolean>>(new Map());
  const [confirmation, setConfirmation] = useState<"status" | "password" | "mfa" | "delete" | null>(null);
  const [feedback, setFeedback] = useState("");
  const user = useQuery({ queryKey: ["user", userId], enabled: Boolean(userId), queryFn: ({ signal }) => apiRequest<UserSummary>(`/api/users/${userId}`, { signal }) });
  const profile = useQuery({ queryKey: ["user-profile", userId], enabled: Boolean(userId), queryFn: ({ signal }) => apiRequest<UserProfile>(`/api/users/${userId}/profile`, { signal }) });
  const schema = useQuery({ queryKey: ["profile-schema", "active"], enabled: canReadSchema, queryFn: ({ signal }) => apiRequest<ProfileAttributeDefinition[]>("/api/profile-schema", { signal }) });
  const applications = useQuery({ queryKey: ["applications", "user-access"], enabled: canReadCatalog, queryFn: ({ signal }) => fetchAllAsPage<ApplicationSummary>("/api/applications", signal) });
  const roles = useQuery({ queryKey: ["roles", "user-access"], enabled: canReadCatalog, queryFn: ({ signal }) => fetchAllAsPage<RoleSummary>("/api/roles", signal) });
  const identity = useForm<UserIdentityForm>({ resolver: zodResolver(userIdentitySchema), defaultValues: userIdentityDefaults() });
  useEffect(() => { if (user.data) identity.reset(userIdentityDefaults(user.data)); }, [identity, user.data]);

  const selectedApplications = useMemo(() => deriveSelection(user.data?.applicationAssignments.filter(item => item.directAccessStatus === "Active").map(item => item.applicationId) ?? [], applicationOverrides), [applicationOverrides, user.data?.applicationAssignments]);
  const selectedRoles = useMemo(() => deriveSelection(user.data?.roleAssignments.filter(item => item.isDirect).map(item => item.roleId) ?? [], roleOverrides), [roleOverrides, user.data?.roleAssignments]);
  const applicationCatalog = useMemo(() => mergeApplications(applications.data?.items ?? [], user.data?.applicationAssignments ?? []), [applications.data?.items, user.data?.applicationAssignments]);
  const roleCatalog = useMemo(() => mergeRoles(roles.data?.items ?? [], user.data?.roleAssignments.filter(item => item.isDirect) ?? []), [roles.data?.items, user.data?.roleAssignments]);
  const updateIdentity = useMutation({ mutationFn: (values: UserIdentityForm) => apiRequest<UserSummary>(`/api/users/${userId}`, { method: "PUT", body: JSON.stringify({ ...userIdentityPayload(values), version: user.data?.version }) }), onSuccess: async (saved) => { queryClient.setQueryData(["user", userId], saved); await queryClient.invalidateQueries({ queryKey: ["users"] }); identity.reset(userIdentityDefaults(saved)); setFeedback("La identidad del usuario quedó actualizada."); } });
  const updateProfile = useMutation({ mutationFn: (attributes: Record<string, unknown>) => apiRequest<UserProfile>(`/api/users/${userId}/profile`, { method: "PUT", body: JSON.stringify({ attributes }) }), onSuccess: (saved) => { queryClient.setQueryData(["user-profile", userId], saved); setFeedback("El perfil universal quedó actualizado."); } });
  const updateAccess = useMutation({ mutationFn: () => apiRequest<UserSummary>(`/api/users/${userId}/access`, { method: "PUT", body: JSON.stringify({ applicationSystemIds: [...selectedApplications], roleIds: [...selectedRoles].filter(roleId => { const catalogRole = roles.data?.items.find(item => item.id === roleId); const existingRole = user.data?.roleAssignments.find(item => item.roleId === roleId); const applicationId = catalogRole?.applicationSystemId ?? existingRole?.applicationId; return applicationId && selectedApplications.has(applicationId); }) }) }), onSuccess: async (saved) => { queryClient.setQueryData(["user", userId], saved); setApplicationOverrides(new Map()); setRoleOverrides(new Map()); await queryClient.invalidateQueries({ queryKey: ["users"] }); setFeedback("El acceso directo quedó actualizado y las sesiones anteriores fueron revocadas."); } });
  const changeStatus = useMutation({ mutationFn: () => apiRequest<void>(`/api/users/${userId}/${user.data?.isActive ? "deactivate" : "activate"}`, { method: "PATCH" }), onSuccess: async () => { setConfirmation(null); await Promise.all([queryClient.invalidateQueries({ queryKey: ["user", userId] }), queryClient.invalidateQueries({ queryKey: ["users"] })]); setFeedback("El estado quedó actualizado y las sesiones anteriores fueron revocadas."); } });
  const forcePassword = useMutation({ mutationFn: () => apiRequest<void>(`/api/users/${userId}/force-password-change`, { method: "POST" }), onSuccess: () => { setConfirmation(null); setFeedback("El cambio de contraseña será obligatorio en el próximo inicio de sesión."); } });
  const approveAccess = useMutation({ mutationFn: (applicationId: string) => apiRequest<void>(`/api/users/${userId}/applications/${applicationId}/approve`, { method: "PATCH" }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["user", userId] }); setFeedback("El acceso pendiente fue aprobado."); } });
  const revokeAccess = useMutation({ mutationFn: (applicationId: string) => apiRequest<void>(`/api/users/${userId}/applications/${applicationId}`, { method: "DELETE" }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["user", userId] }); setFeedback("El acceso directo fue revocado y sus sesiones quedaron invalidadas."); } });
  const resetMfa = useMutation({ mutationFn: (proofToken: string) => apiRequest<void>(`/api/users/${userId}/mfa`, { method: "DELETE", headers: { "X-AuthCenter-Reauthentication": proofToken } }), onSuccess: async () => { setConfirmation(null); await queryClient.invalidateQueries({ queryKey: ["user", userId] }); setFeedback("MFA fue restablecido después de verificar tu identidad."); } });
  const deleteUser = useMutation({ mutationFn: (proofToken: string) => apiRequest<void>(`/api/users/${userId}`, { method: "DELETE", headers: { "X-AuthCenter-Reauthentication": proofToken } }), onSuccess: async () => { setConfirmation(null); await queryClient.invalidateQueries({ queryKey: ["users"] }); window.location.assign("/admin-v2/users"); } });

  if (user.isPending) return <PageState title="Cargando usuario" busy />;
  if (user.isError || !user.data) return <PageState title="No pudimos cargar el usuario" detail={errorMessage(user.error)} tone="error" />;
  const current = user.data;
  const error = updateIdentity.error ?? updateProfile.error ?? updateAccess.error ?? changeStatus.error ?? forcePassword.error ?? approveAccess.error ?? revokeAccess.error ?? resetMfa.error ?? deleteUser.error;
  return <>
    <Breadcrumbs items={[{ label: "Usuarios", to: "/users" }, { label: current.fullName }]} />
    <PageHeader eyebrow="Directorio universal" title={current.fullName} description={`${current.email} · ${current.isExternalUser ? "Identidad federada" : "Identidad local"}`} actions={<><HistoryLink entityName="ApplicationUser" entityId={userId} /><Link className="button button--secondary" to="/users">Volver</Link></>} />
    {feedback ? <p className="alert alert--success" role="status">{feedback}</p> : null}<SaveError error={error} onReload={() => { updateIdentity.reset(); void user.refetch().then((fresh) => { if (fresh.data) identity.reset(userIdentityDefaults(fresh.data)); }); }} />
    <div className="profile-summary"><div><span>Estado</span><StatusBadge active={current.isActive} /></div><div><span>Último acceso</span><strong>{formatDate(current.lastLoginAt)}</strong></div><div><span>MFA</span><strong>{current.mfaEnabled ? "Configurado" : "Sin configurar"}</strong></div><div><span>Grupos</span><strong>{current.groupMemberships.length}</strong></div></div>
    <form className="settings-form" onSubmit={(event) => void identity.handleSubmit((values) => updateIdentity.mutateAsync(values))(event)}><fieldset className="settings-fieldset" disabled={!canWrite}><section className="settings-panel"><div className="settings-panel__heading"><div><h2>Identidad</h2><p>Datos canónicos visibles en las aplicaciones conectadas.</p></div></div><label className="field"><span>Nombre completo</span><input {...identity.register("fullName")} />{identity.formState.errors.fullName ? <small className="field-error">{identity.formState.errors.fullName.message}</small> : null}</label><label className="field"><span>Fotografía HTTPS</span><input type="url" {...identity.register("pictureUrl")} />{identity.formState.errors.pictureUrl ? <small className="field-error">{identity.formState.errors.pictureUrl.message}</small> : null}</label></section></fieldset>{canWrite ? <div className="form-footer"><button className="button" disabled={updateIdentity.isPending}>Guardar identidad</button></div> : null}</form>
    <ProfilePanel key={`${profile.dataUpdatedAt}-${schema.dataUpdatedAt}`} profile={profile.data} definitions={schema.data ?? []} editable={canWrite && canReadSchema} busy={updateProfile.isPending} onSave={(values) => updateProfile.mutate(profilePayload(schema.data ?? [], values))} />
    <AccessPanel user={current} applications={applicationCatalog} roles={roleCatalog} selectedApplications={selectedApplications} selectedRoles={selectedRoles} readable={canReadCatalog} editable={canWrite && canReadCatalog && current.isActive} busy={updateAccess.isPending} onApplicationChange={(id, enabled) => { setApplicationOverrides(map => new Map(map).set(id, enabled)); if (!enabled) setRoleOverrides(map => { const next = new Map(map); roleCatalog.filter(role => role.applicationSystemId === id).forEach(role => next.set(role.id, false)); return next; }); }} onRoleChange={(id, enabled) => setRoleOverrides(map => new Map(map).set(id, enabled))} onSave={() => updateAccess.mutate()} onApprove={(id) => approveAccess.mutate(id)} onRevoke={(id) => revokeAccess.mutate(id)} />
    <section className="settings-panel settings-panel--actions"><div className="settings-panel__heading"><div><h2>Grupos y herencia</h2><p>Las asignaciones heredadas sólo pueden cambiarse desde el grupo de origen.</p></div></div>{current.groupMemberships.length ? <div className="assignment-list">{current.groupMemberships.map(item => <div className="assignment-item" key={item.groupId}><span><strong>{item.groupName}</strong><small>Miembro desde {formatDate(item.addedAt)}</small></span><span><StatusBadge active={item.isGroupActive} /><Link className="button button--small button--secondary" to={`/groups/${item.groupId}`}>Ver grupo</Link></span></div>)}</div> : <p className="muted">No pertenece a grupos.</p>}</section>
    {canWrite ? <section className="settings-panel settings-panel--actions"><div className="settings-panel__heading"><div><h2>Operaciones de cuenta</h2><p>Los cambios sensibles revocan sesiones y quedan auditados.</p></div></div>{current.mustChangePassword ? <p className="alert alert--info">Ya tiene un cambio de contraseña pendiente.</p> : null}<div className="button-group"><button type="button" className="button button--secondary" disabled={!current.hasLocalPassword} onClick={() => setConfirmation("password")}>Forzar cambio de contraseña</button><button type="button" className="button button--secondary" disabled={!current.mfaEnabled} onClick={() => setConfirmation("mfa")}>Restablecer MFA</button><button type="button" className={`button ${current.isActive ? "button--danger-quiet" : "button--secondary"}`} onClick={() => setConfirmation("status")}>{current.isActive ? "Desactivar usuario" : "Activar usuario"}</button><button type="button" className="button button--danger" onClick={() => setConfirmation("delete")}>Anonimizar usuario</button></div></section> : null}
    <ConfirmDialog open={confirmation === "status"} title={`${current.isActive ? "Desactivar" : "Activar"} usuario`} detail="El estado y el acceso efectivo se recalcularán inmediatamente; las sesiones anteriores serán revocadas." confirmLabel={current.isActive ? "Desactivar" : "Activar"} dangerous={current.isActive} busy={changeStatus.isPending} error={changeStatus.error} onCancel={() => setConfirmation(null)} onConfirm={() => changeStatus.mutate()} />
    <ConfirmDialog open={confirmation === "password"} title="Forzar cambio de contraseña" detail="La persona deberá elegir una contraseña nueva en el próximo inicio de sesión y sus sesiones actuales serán revocadas." confirmLabel="Forzar cambio" busy={forcePassword.isPending} error={forcePassword.error} onCancel={() => setConfirmation(null)} onConfirm={() => forcePassword.mutate()} />
    <ReauthenticationDialog open={confirmation === "mfa"} purpose="admin.mfa.reset" title="Restablecer MFA" detail={`Eliminarás todos los factores MFA de ${current.fullName}. Verifica primero tu propia identidad administrativa.`} confirmLabel="Verificar y restablecer" onCancel={() => setConfirmation(null)} onProof={(proof) => resetMfa.mutateAsync(proof)} />
    <ReauthenticationDialog open={confirmation === "delete"} purpose="admin.user.delete" title="Anonimizar usuario" detail={`Esta operación anonimiza permanentemente a ${current.fullName}, revoca sus sesiones y conserva únicamente la evidencia de auditoría.`} confirmLabel="Verificar y anonimizar" dangerous onCancel={() => setConfirmation(null)} onProof={(proof) => deleteUser.mutateAsync(proof)} />
  </>;
}

function ProfilePanel({ profile, definitions, editable, busy, onSave }: { profile: UserProfile | undefined; definitions: ProfileAttributeDefinition[]; editable: boolean; busy: boolean; onSave: (values: Record<string, unknown>) => void }) {
  const current = new Map(profile?.attributes.map(attribute => [attribute.key, attribute.value]) ?? []);
  const [values, setValues] = useState<Record<string, unknown>>(() => Object.fromEntries(definitions.map(definition => [definition.key, current.get(definition.key) ?? definition.defaultValue ?? ""])));
  return <section className="settings-panel settings-panel--actions"><div className="settings-panel__heading"><div><h2>Perfil universal</h2><p>Atributos con tipo que comparten la automatización, la federación y SCIM.</p></div>{profile ? <span className={`tag ${profile.isValid ? "" : "tag--warning"}`}>{profile.isValid ? "Completo" : "Incompleto"}</span> : null}</div>{!profile ? <p className="muted">Cargando perfil…</p> : definitions.length ? <div className="form-grid">{definitions.map(definition => <ProfileField key={definition.id} definition={definition} value={values[definition.key]} disabled={!editable} onChange={(value) => setValues(state => ({ ...state, [definition.key]: value }))} />)}</div> : <div className="assignment-list">{profile.attributes.map(attribute => <div className="assignment-item" key={attribute.key}><span><strong>{attribute.key}</strong><small>{attribute.isDefault ? "Valor predeterminado" : "Valor asignado"}</small></span><span>{String(attribute.value)}</span></div>)}</div>}{profile?.missingRequiredAttributes.length ? <p className="alert alert--error">Faltan atributos obligatorios: {profile.missingRequiredAttributes.join(", ")}.</p> : null}{editable && definitions.length ? <div className="form-footer"><button type="button" className="button" disabled={busy} onClick={() => onSave(values)}>{busy ? "Guardando…" : "Guardar perfil universal"}</button></div> : null}</section>;
}

function ProfileField({ definition, value, disabled, onChange }: { definition: ProfileAttributeDefinition; value: unknown; disabled: boolean; onChange: (value: unknown) => void }) {
  const label = <span>{definition.displayName}{definition.isRequired ? " *" : ""}</span>;
  if (definition.dataType === "Boolean") return <label className="checkbox-field"><input type="checkbox" checked={Boolean(value)} disabled={disabled} onChange={event => onChange(event.target.checked)} />{label}</label>;
  if (definition.allowedValues.length) return <label className="field">{label}<select value={String(value)} disabled={disabled} onChange={event => onChange(coerceProfileValue(definition, event.target.value))}><option value="">Selecciona…</option>{definition.allowedValues.map(option => <option key={String(option)} value={String(option)}>{String(option)}</option>)}</select></label>;
  const type = definition.dataType === "Date" ? "date" : definition.dataType === "DateTime" ? "datetime-local" : definition.dataType === "Integer" || definition.dataType === "Decimal" ? "number" : "text";
  return <label className="field">{label}<input type={type} value={formatProfileInput(definition, value)} disabled={disabled} min={definition.minimumNumber ?? undefined} max={definition.maximumNumber ?? undefined} minLength={definition.minLength ?? undefined} maxLength={definition.maxLength ?? undefined} onChange={event => onChange(coerceProfileValue(definition, event.target.value))} />{definition.description ? <small>{definition.description}</small> : null}</label>;
}

function AccessPanel({ user, applications, roles, selectedApplications, selectedRoles, readable, editable, busy, onApplicationChange, onRoleChange, onSave, onApprove, onRevoke }: { user: UserSummary; applications: ApplicationSummary[]; roles: RoleSummary[]; selectedApplications: Set<string>; selectedRoles: Set<string>; readable: boolean; editable: boolean; busy: boolean; onApplicationChange: (id: string, enabled: boolean) => void; onRoleChange: (id: string, enabled: boolean) => void; onSave: () => void; onApprove: (id: string) => void; onRevoke: (id: string) => void }) {
  return <section className="settings-panel settings-panel--actions"><div className="settings-panel__heading"><div><h2>Acceso directo y heredado</h2><p>El acceso directo es editable aquí; la herencia muestra cada grupo de origen.</p></div></div>{!readable ? <p className="alert alert--info">Necesitas lectura de aplicaciones y roles para administrar el acceso directo.</p> : <div className="access-grid"><fieldset className="check-group"><legend>Aplicaciones</legend><div className="permission-matrix">{applications.map(application => { const assignment = user.applicationAssignments.find(item => item.applicationId === application.id); return <label className="permission-option" key={application.id}><input type="checkbox" checked={selectedApplications.has(application.id)} disabled={!editable || !application.isActive} onChange={event => onApplicationChange(application.id, event.target.checked)} /><span><strong>{application.name}</strong><small className="mono">{application.code}</small><SourceLabels direct={assignment?.directAccessStatus === "Active"} inherited={assignment?.inheritedFromGroups ?? []} /></span></label>; })}</div></fieldset><fieldset className="check-group"><legend>Roles</legend><div className="permission-matrix">{roles.filter(role => role.applicationSystemId).map(role => { const assignment = user.roleAssignments.find(item => item.roleId === role.id); return <label className="permission-option" key={role.id}><input type="checkbox" checked={selectedRoles.has(role.id)} disabled={!editable || !role.isActive || !selectedApplications.has(role.applicationSystemId!)} onChange={event => onRoleChange(role.id, event.target.checked)} /><span><strong>{role.name}</strong><small>{applications.find(application => application.id === role.applicationSystemId)?.name ?? "Aplicación"}</small><SourceLabels direct={assignment?.isDirect ?? false} inherited={assignment?.inheritedFromGroups ?? []} /></span></label>; })}</div></fieldset></div>}{user.applicationAssignments.some(item => item.directAccessStatus === "Pending") ? <div className="assignment-list"><h3>Accesos pendientes</h3>{user.applicationAssignments.filter(item => item.directAccessStatus === "Pending").map(item => <div className="assignment-item" key={item.applicationId}><span><strong>{item.applicationName}</strong><small>{item.applicationCode}</small></span>{editable ? <span className="button-group"><button type="button" className="button button--small" onClick={() => onApprove(item.applicationId)}>Aprobar</button><button type="button" className="button button--small button--danger-quiet" onClick={() => onRevoke(item.applicationId)}>Revocar</button></span> : null}</div>)}</div> : null}{editable ? <div className="form-footer"><button type="button" className="button" disabled={busy} onClick={onSave}>{busy ? "Guardando…" : "Guardar acceso directo"}</button></div> : null}</section>;
}

function SourceLabels({ direct, inherited }: { direct: boolean; inherited: Array<{ groupId: string; groupName: string; isActive: boolean }> }) { return <span className="source-labels">{direct ? <span className="tag tag--direct">Directo</span> : null}{inherited.map(group => <span className={`tag ${group.isActive ? "tag--inherited" : "tag--inactive"}`} key={group.groupId}>Heredado: {group.groupName}</span>)}</span>; }
function coerceProfileValue(definition: ProfileAttributeDefinition, value: string): unknown { if (value === "") return ""; if (definition.dataType === "Integer" || definition.dataType === "Decimal") return Number(value); if (definition.dataType === "Boolean") return value === "true"; return value; }
function formatProfileInput(definition: ProfileAttributeDefinition, value: unknown): string { if (definition.dataType === "DateTime" && typeof value === "string" && value) return value.replace(/Z$/, "").slice(0, 16); return String(value ?? ""); }
function profilePayload(definitions: ProfileAttributeDefinition[], values: Record<string, unknown>): Record<string, unknown> { return Object.fromEntries(definitions.map(definition => { const value = values[definition.key]; if (value === "" || value === undefined) return [definition.key, null]; if (definition.dataType === "DateTime" && typeof value === "string") return [definition.key, new Date(value).toISOString()]; return [definition.key, value]; })); }
function mergeApplications(catalog: ApplicationSummary[], assigned: UserSummary["applicationAssignments"]): ApplicationSummary[] { const merged = new Map(catalog.map(item => [item.id, item])); for (const item of assigned) if (!merged.has(item.applicationId)) merged.set(item.applicationId, { id: item.applicationId, code: item.applicationCode, name: item.applicationName, description: "Asignación existente fuera de la primera página del catálogo.", isActive: item.isApplicationActive, createdAt: "", updatedAt: null, branding: null }); return [...merged.values()].sort((left, right) => left.code.localeCompare(right.code)); }
function mergeRoles(catalog: RoleSummary[], assigned: UserSummary["roleAssignments"]): RoleSummary[] { const merged = new Map(catalog.map(item => [item.id, item])); for (const item of assigned) if (!merged.has(item.roleId)) merged.set(item.roleId, { id: item.roleId, name: item.roleName, description: "Asignación existente fuera de la primera página del catálogo.", applicationSystemId: item.applicationId, isSystemRole: item.isSystemRole, isActive: item.isRoleActive, createdAt: "", permissions: [] }); return [...merged.values()].sort((left, right) => left.name.localeCompare(right.name)); }
function deriveSelection(initial: string[], overrides: Map<string, boolean>): Set<string> { const selected = new Set(initial); for (const [id, enabled] of overrides) { if (enabled) selected.add(id); else selected.delete(id); } return selected; }
