namespace AuthCenter.Domain.Events;

/// <summary>A type of audit event an event hook can subscribe to, with the area it belongs to.</summary>
public sealed record EventTypeInfo(string Type, string Category);

/// <summary>
/// The audit events AuthCenter records, which event hooks subscribe to by type (or with
/// <see cref="Wildcard"/>). A unit test keeps this list in step with the audit calls in the code.
/// </summary>
public static class EventTypes
{
    public const string Wildcard = "*";

    private static readonly (string Category, string[] Types)[] Groups =
    [
        ("authentication",
        [
            "LOGIN_SUCCESS", "LOGIN_FAILED", "LOGIN_LOCKED_OUT", "LOGIN_MAGIC_LINK_SUCCESS", "MAGIC_LINK_SENT", "MAGIC_LINK_NOOP",
            "LOGIN_GOOGLE_SUCCESS", "LOGIN_MICROSOFT_SUCCESS", "LOGIN_GITHUB_SUCCESS", "LOGIN_APPLE_SUCCESS",
            "PASSWORD_CHANGE_REQUIRED", "FORCED_PASSWORD_CHANGED", "FORGOT_PASSWORD_SENT", "FORGOT_PASSWORD_NOOP", "PASSWORD_RESET",
            "REAUTHENTICATION_SUCCESS", "REAUTHENTICATION_FAILED", "ACCESS_POLICY_DENIED", "ACCESS_POLICY_DENIED_AFTER_MFA"
        ]),
        ("mfa",
        [
            "MFA_REQUIRED", "MFA_SETUP_REQUIRED", "MFA_STEP_UP_REQUIRED", "MFA_SETUP_STARTED", "MFA_ENABLED", "MFA_DISABLED", "MFA_ADMIN_RESET",
            "MFA_ENROLLED_AT_SIGN_IN", "MFA_VERIFY_SUCCESS", "MFA_VERIFY_FAILED", "MFA_SKIPPED_TRUSTED_DEVICE",
            "MFA_BACKUP_CODES_REGENERATED", "MFA_BACKUP_CODE_USED", "MFA_BACKUP_CODE_EXHAUSTED",
            "MFA_EMAIL_OTP_SETUP_SENT", "MFA_EMAIL_OTP_ENABLED", "MFA_EMAIL_OTP_SENT", "MFA_EMAIL_OTP_VERIFICATION_SENT"
        ]),
        ("passkeys",
        [
            "PASSKEY_REGISTERED", "PASSKEY_REGISTRATION_FAILED", "PASSKEY_RENAMED", "PASSKEY_REMOVED", "PASSKEY_LOGIN_SUCCESS", "PASSKEY_LOGIN_FAILED",
            "PASSKEY_REQUIRED", "PASSKEY_ENROLLMENT_REQUIRED", "PASSKEY_ENROLLED_AT_SIGN_IN"
        ]),
        ("sessions",
        [
            "LOGOUT", "REVOKE_SESSION", "REVOKE_ALL_SESSIONS", "SSO_SESSION_ENDED",
            "TRUSTED_DEVICE_CREATED", "TRUSTED_DEVICE_REVOKED", "TRUSTED_DEVICES_REVOKED"
        ]),
        ("tokens",
        [
            "TOKEN_REFRESHED", "TOKEN_REVOKED", "REFRESH_TOKEN_EXPIRED", "REFRESH_TOKEN_INVALID", "REFRESH_TOKEN_REUSE_DETECTED",
            "REFRESH_TOKEN_CONCURRENT_REUSE_DETECTED"
        ]),
        ("oauth",
        [
            "OAUTH_AUTHORIZATION_GRANTED", "OAUTH_ACCESS_DENIED", "OAUTH_CONSENT_DENIED", "OAUTH_CONSENT_REVOKED", "OAUTH_CODE_EXCHANGED",
            "OAUTH_CLIENT_CREDENTIALS_ISSUED", "OAUTH_TOKEN_EXCHANGED", "OAUTH_TOKEN_REVOKED", "OAUTH_REFRESH_TOKEN_ROTATED",
            "OAUTH_REFRESH_ACCESS_REVOKED", "OAUTH_REFRESH_TOKEN_REUSE_DETECTED", "OAUTH_REFRESH_TOKEN_CONCURRENT_REUSE_DETECTED",
            "OAUTH_CLIENT_CREATED", "OAUTH_CLIENT_UPDATED", "OAUTH_CLIENT_ACTIVATED", "OAUTH_CLIENT_DEACTIVATED", "OAUTH_CLIENT_SECRET_ROTATED",
            "OAUTH_CLIENT_ACTIVATION_REJECTED", "OAUTH_CLIENT_DEACTIVATION_REJECTED", "OAUTH_CLIENT_SECRET_ROTATION_REJECTED"
        ]),
        ("saml",
        [
            "SAML_ASSERTION_ISSUED", "SAML_SSO_DENIED", "SAML_REQUEST_REJECTED", "SAML_LOGOUT_COMPLETED",
            "SAML_SERVICE_PROVIDER_CREATED", "SAML_SERVICE_PROVIDER_UPDATED", "SAML_SERVICE_PROVIDER_DELETED"
        ]),
        ("federation",
        [
            "FEDERATION_LOGIN_STARTED", "FEDERATION_LOGIN_SUCCESS", "FEDERATION_LOGIN_FAILED", "FEDERATION_ACCESS_DENIED", "FEDERATION_BINDING_MISMATCH",
            "FEDERATION_USER_JIT_PROVISIONED", "FEDERATION_GROUPS_SYNCED", "FEDERATION_LINK_STARTED", "FEDERATION_LINK_VERIFIED",
            "FEDERATION_IDENTITY_LINKED", "FEDERATION_LINK_REJECTED", "FEDERATION_LINK_USER_MISMATCH",
            "FEDERATION_PROVIDER_CREATED", "FEDERATION_PROVIDER_UPDATED", "FEDERATION_PROVIDER_DELETED", "FEDERATION_CONNECTION_TESTED",
            "FEDERATION_ROUTING_RULE_CREATED", "FEDERATION_ROUTING_RULE_UPDATED", "FEDERATION_ROUTING_RULE_DELETED", "FEDERATION_ROUTING_RULES_REORDERED",
            "FEDERATION_CHANGE_REJECTED", "LINK_PROVIDER", "UNLINK_PROVIDER"
        ]),
        ("users",
        [
            "USER_REGISTERED", "USER_REGISTERED_GOOGLE", "USER_REGISTERED_MICROSOFT", "USER_REGISTERED_GITHUB", "USER_REGISTERED_APPLE",
            "USER_CREATED", "USER_INVITED", "USER_ACTIVATED", "USER_DEACTIVATED", "USER_ANONYMIZED", "USER_PROFILE_CORE_UPDATED", "USER_PROFILE_UPDATED",
            "USER_PASSWORD_CHANGE_FORCED", "USER_ROLE_ASSIGNED", "USER_ROLE_REMOVED", "USER_DIRECT_ACCESS_REPLACED",
            "USER_APPLICATION_ACCESS_GRANTED", "USER_APPLICATION_ACCESS_PENDING", "USER_APPLICATION_ACCESS_APPROVED", "USER_APPLICATION_ACCESS_REVOKED",
            "SUPER_ADMIN_REMOVAL_REJECTED"
        ]),
        ("account",
        [
            "EMAIL_CONFIRMED", "EMAIL_CONFIRMATION_RESENT", "CHANGE_PASSWORD", "REQUEST_EMAIL_CHANGE", "CONFIRM_EMAIL_CHANGE", "DELETE_ACCOUNT"
        ]),
        ("groups",
        [
            "DIRECTORY_GROUP_CREATED", "DIRECTORY_GROUP_UPDATED", "DIRECTORY_GROUP_ACTIVATED", "DIRECTORY_GROUP_DEACTIVATED",
            "DIRECTORY_GROUP_MEMBER_ADDED", "DIRECTORY_GROUP_MEMBER_REMOVED", "DIRECTORY_GROUP_ROLE_ASSIGNED", "DIRECTORY_GROUP_ROLE_REMOVED",
            "DIRECTORY_GROUP_APPLICATION_ASSIGNED", "DIRECTORY_GROUP_APPLICATION_REMOVED", "DIRECTORY_GROUP_ACCESS_REPLACED",
            "DYNAMIC_GROUP_RULE_CREATED", "DYNAMIC_GROUP_RULE_UPDATED", "DYNAMIC_GROUP_RULE_DELETED"
        ]),
        ("roles-permissions",
        [
            "ROLE_CREATED", "ROLE_UPDATED", "ROLE_ACTIVATED", "ROLE_DEACTIVATED", "ROLE_PERMISSION_GRANTED", "ROLE_PERMISSION_REVOKED", "ROLE_PERMISSIONS_REPLACED",
            "PERMISSION_CREATED", "PERMISSION_UPDATED", "PERMISSION_ACTIVATED", "PERMISSION_DEACTIVATED"
        ]),
        ("applications",
        [
            "APPLICATION_CREATED", "APPLICATION_UPDATED", "APPLICATION_ACTIVATED", "APPLICATION_DEACTIVATED", "APPLICATION_BRANDING_UPDATED",
            "API_RESOURCE_CREATED", "API_RESOURCE_UPDATED"
        ]),
        ("access-policies",
        [
            "ACCESS_POLICY_DRAFT_CREATED", "ACCESS_POLICY_DRAFT_RULE_CREATED", "ACCESS_POLICY_DRAFT_RULE_UPDATED", "ACCESS_POLICY_DRAFT_RULE_DELETED",
            "ACCESS_POLICY_VERSION_PUBLISHED", "ACCESS_POLICY_PUBLISH_REJECTED"
        ]),
        ("profiles",
        [
            "PROFILE_ATTRIBUTE_DEFINITION_CREATED", "PROFILE_ATTRIBUTE_DEFINITION_UPDATED", "PROFILE_ATTRIBUTE_DEFINITION_DEACTIVATED",
            "PROFILE_MAPPING_CREATED", "PROFILE_MAPPING_UPDATED", "PROFILE_MAPPING_DELETED"
        ]),
        ("governance",
        [
            "APPLICATION_GOVERNANCE_UPDATED", "ACCESS_REQUEST_CREATED", "ACCESS_REQUEST_APPROVED", "ACCESS_REQUEST_REJECTED",
            "ACCESS_REQUEST_CANCELLED", "ACCESS_REQUEST_EXPIRED", "ACCESS_REVIEW_STARTED", "ACCESS_REVIEW_DECIDED", "ACCESS_REVIEW_COMPLETED",
            "ACCESS_REVIEW_CANCELLED", "SOD_RULE_CREATED", "SOD_RULE_UPDATED", "SOD_RULE_DELETED", "SOD_CONFLICT_BLOCKED"
        ]),
        ("provisioning",
        [
            "SCIM_USER_CREATED", "SCIM_USER_UPDATED", "SCIM_USER_DEPROVISIONED", "SCIM_GROUP_CREATED", "SCIM_GROUP_UPDATED", "SCIM_GROUP_DEPROVISIONED",
            "PROVISIONING_TOKEN_CREATED", "PROVISIONING_TOKEN_ROTATED", "PROVISIONING_TOKEN_REVOKED", "PROVISIONING_TOKEN_MUTATION_REJECTED"
        ]),
        ("event-hooks",
        [
            "EVENT_HOOK_CREATED", "EVENT_HOOK_UPDATED", "EVENT_HOOK_VERIFIED", "EVENT_HOOK_VERIFICATION_REJECTED", "EVENT_HOOK_DISABLED",
            "EVENT_HOOK_SECRET_ROTATED", "EVENT_HOOK_DELIVERY_REPLAYED"
        ]),
        ("administration", ["ADMIN_MUTATION_REJECTED", "SYSTEM_LOG_EXPORTED"])
    ];

    public static IReadOnlyList<EventTypeInfo> All { get; } =
        Groups.SelectMany(group => group.Types.Select(type => new EventTypeInfo(type, group.Category))).ToList();

    private static readonly HashSet<string> Known = new(All.Select(item => item.Type), StringComparer.Ordinal);

    public static bool IsKnown(string type) => Known.Contains(type);
}
